/* SPDX-License-Identifier: GPL-2.0 */
#ifndef _LINUX_FRGMARK_H
#define _LINUX_FRGMARK_H

#include <linux/init.h>
#include <linux/types.h>

#define FRGMARK_STAGE_IMEM_READY			0x01
#define FRGMARK_STAGE_SETUP_ARCH_DONE			0x02
#define FRGMARK_STAGE_TRAP_INIT_DONE			0x03
#define FRGMARK_STAGE_MM_INIT_DONE			0x04
#define FRGMARK_STAGE_SCHED_INIT_DONE			0x05
#define FRGMARK_STAGE_SOFTIRQ_INIT_DONE			0x06
#define FRGMARK_STAGE_TIMEKEEPING_DONE			0x07
#define FRGMARK_STAGE_TIME_INIT_DONE			0x08
#define FRGMARK_STAGE_DRIVER_INIT_BEGIN			0x09
#define FRGMARK_STAGE_DRIVER_INIT_DONE			0x0a
#define FRGMARK_STAGE_KERNEL_INIT_BEGIN			0x0b
#define FRGMARK_STAGE_KERNEL_INIT_FREEABLE_DONE		0x0c
#define FRGMARK_STAGE_INITCALLS_BEGIN			0x0d
#define FRGMARK_STAGE_INITCALLS_DONE			0x0e
#define FRGMARK_STAGE_KERNEL_FREEABLE_DONE		0x0f
#define FRGMARK_STAGE_EXEC_RAMDISK_INIT			0x10
#define FRGMARK_STAGE_EXEC_RAMDISK_INIT_FAILED		0x11
#define FRGMARK_STAGE_EXEC_CMDLINE_INIT			0x12
#define FRGMARK_STAGE_EXEC_FALLBACK_INIT		0x13
#define FRGMARK_STAGE_CONSOLE_INIT_DONE			0x14
#define FRGMARK_STAGE_USERSPACE_REACHED			0x15
#define FRGMARK_STAGE_RECOVERY_TIMEOUT_REBOOT		0x16
#define FRGMARK_STAGE_USERSPACE_ACK			0x17
#define FRGMARK_STAGE_REST_INIT_BEGIN			0x18
#define FRGMARK_STAGE_REST_INIT_KERNEL_INIT_THREAD_DONE	0x19
#define FRGMARK_STAGE_REST_INIT_KTHREADD_THREAD_DONE	0x1a
#define FRGMARK_STAGE_REST_INIT_KTHREADD_COMPLETE_DONE	0x1b
#define FRGMARK_STAGE_REST_INIT_SCHEDULE_ENTER		0x1c
#define FRGMARK_STAGE_KERNEL_INIT_WAIT_KTHREADD_BEGIN	0x1d
#define FRGMARK_STAGE_KERNEL_INIT_WAIT_KTHREADD_DONE	0x1e
#define FRGMARK_STAGE_KERNEL_INIT_SMP_PREPARE_BEGIN	0x1f

#define FRGMARK_STAGE_HEAD_ENTRY			0x70
#define FRGMARK_STAGE_HEAD_ARGS_PRESERVED		0x71
#define FRGMARK_STAGE_HEAD_EL2_DONE			0x72
#define FRGMARK_STAGE_HEAD_PAGETABLES_DONE		0x73
#define FRGMARK_STAGE_HEAD_CPU_SETUP_DONE		0x74
#define FRGMARK_STAGE_HEAD_PRIMARY_SWITCH		0x75

#define FRGMARK_STAGE_SETUP_EARLY_IOREMAP_READY	0x80
#define FRGMARK_STAGE_SETUP_FDT_DONE			0x81
#define FRGMARK_STAGE_SETUP_EARLY_PARAM_DONE		0x82
#define FRGMARK_STAGE_SETUP_MEMBLOCK_DONE		0x83
#define FRGMARK_STAGE_SETUP_PAGING_DONE		0x84
#define FRGMARK_STAGE_SETUP_BEFORE_IOREMAP_RESET	0x85
#define FRGMARK_STAGE_SETUP_IOREMAP_RESET_DONE		0x86
#define FRGMARK_STAGE_SETUP_PSCI_DONE			0x87
#define FRGMARK_STAGE_SETUP_BOOTCPU_OPS_DONE		0x88
#define FRGMARK_STAGE_SETUP_SMP_CPUS_DONE		0x89
#define FRGMARK_STAGE_SETUP_MPIDR_HASH_DONE		0x8a
#define FRGMARK_STAGE_SETUP_BOOT_ARGS_DONE		0x8b
#define FRGMARK_STAGE_SETUP_RANDOM_POOL_DONE		0x8c
#define FRGMARK_STAGE_SETUP_IOREMAP_RESET_RETURNED	0x8d
#define FRGMARK_STAGE_SETUP_BEFORE_RESET_SPLASH_DONE	0x8e
#define FRGMARK_STAGE_SETUP_IOREMAP_RESET_SKIPPED	0x8f

#define FRGMARK_STAGE_INITCALL_EARLY_DONE		0x50
#define FRGMARK_STAGE_INITCALL_CORE_DONE		0x51
#define FRGMARK_STAGE_INITCALL_POSTCORE_DONE		0x52
#define FRGMARK_STAGE_INITCALL_ARCH_DONE		0x53
#define FRGMARK_STAGE_INITCALL_SUBSYS_DONE		0x54
#define FRGMARK_STAGE_INITCALL_FS_DONE			0x55
#define FRGMARK_STAGE_INITCALL_DEVICE_DONE		0x56
#define FRGMARK_STAGE_INITCALL_LATE_DONE		0x57
#define FRGMARK_STAGE_INITCALL_LEVEL_BASE		FRGMARK_STAGE_INITCALL_EARLY_DONE
#define FRGMARK_STAGE_RECOVERY_NO_BCB_GRACE		0x5e
#define FRGMARK_STAGE_RECOVERY_NO_BCB_RESET		0x5f

#define FRGMARK_STAGE_KERNEL_INIT_SMP_PREPARE_DONE	0x60
#define FRGMARK_STAGE_KERNEL_INIT_WORKQUEUE_DONE	0x61
#define FRGMARK_STAGE_KERNEL_INIT_BCB_KICK_DONE		0x62
#define FRGMARK_STAGE_KERNEL_INIT_PRE_SMP_INITCALLS_DONE	0x63
#define FRGMARK_STAGE_KERNEL_INIT_LOCKUP_DETECTOR_DONE	0x64
#define FRGMARK_STAGE_KERNEL_INIT_SMP_INIT_DONE		0x65
#define FRGMARK_STAGE_KERNEL_INIT_SCHED_SMP_DONE	0x66
#define FRGMARK_STAGE_KERNEL_INIT_PAGE_ALLOC_LATE_DONE	0x67
#define FRGMARK_STAGE_KERNEL_INIT_BASIC_SETUP_BEGIN	0x68
#define FRGMARK_STAGE_KERNEL_INIT_BASIC_SETUP_DONE	0x69

#define FRGMARK_STAGE_MSM_DRM_REGISTER_BEGIN		0x20
#define FRGMARK_STAGE_MSM_DRM_REGISTER_DONE		0x21
#define FRGMARK_STAGE_MSM_DRM_PROBE_BEGIN		0x22
#define FRGMARK_STAGE_MSM_DRM_COMPONENTS_DONE		0x23
#define FRGMARK_STAGE_MSM_DRM_BIND_BEGIN		0x24
#define FRGMARK_STAGE_MSM_DRM_DEV_REGISTER_DONE		0x25
#define FRGMARK_STAGE_MSM_DRM_SPLASH_DONE		0x26
#define FRGMARK_STAGE_MSM_DRM_FBDEV_DONE		0x27
#define FRGMARK_STAGE_MSM_DRM_REGISTER_FAILED		0x2f

#define FRGMARK_STAGE_DSI_REGISTER_BEGIN		0x30
#define FRGMARK_STAGE_DSI_REGISTER_DONE			0x31
#define FRGMARK_STAGE_DSI_DISPLAY_PROBE_BEGIN		0x32
#define FRGMARK_STAGE_DSI_DISPLAY_ACTIVE_INIT_BEGIN	0x33
#define FRGMARK_STAGE_DSI_DISPLAY_ACTIVE_INIT_DONE	0x34
#define FRGMARK_STAGE_DSI_DISPLAY_COMPONENT_DONE	0x35
#define FRGMARK_STAGE_DSI_REGISTER_FAILED		0x3f

#define FRGMARK_STAGE_HEARTBEAT_BASE			0x40
#define FRGMARK_STAGE_HEARTBEAT_LAST			0x4f

#ifdef CONFIG_ARM64
void __init frgmark_init_iomap(void);
void __init frgmark_early(u8 stage);
void __init frgmark_linear_ramoops(u8 stage);
void __init frgmark_recovery_timeout_arm(void);
void frgmark_recovery_bcb_kick(const char *reason);
void frgmark_userspace_reached(void);
void frgmark(u8 stage);
#else
static inline void frgmark_init_iomap(void) {}
static inline void frgmark_early(u8 stage) {}
static inline void frgmark_linear_ramoops(u8 stage) {}
static inline void frgmark_recovery_timeout_arm(void) {}
static inline void frgmark_recovery_bcb_kick(const char *reason) {}
static inline void frgmark_userspace_reached(void) {}
static inline void frgmark(u8 stage) {}
#endif

#endif /* _LINUX_FRGMARK_H */
