/* SPDX-License-Identifier: GPL-2.0 */
#ifndef _LINUX_FRGMARK_H
#define _LINUX_FRGMARK_H

#include <linux/init.h>
#include <linux/types.h>

#define FRGMARK_STAGE_IMEM_READY			0x01
#define FRGMARK_STAGE_SETUP_ARCH_DONE			0x02
#define FRGMARK_STAGE_TRAP_INIT_DONE			0x03
#define FRGMARK_STAGE_MM_INIT_DONE			0x04
#define FRGMARK_STAGE_SCHED_INIT_DONE			0x05
#define FRGMARK_STAGE_SOFTIRQ_INIT_DONE			0x06
#define FRGMARK_STAGE_TIMEKEEPING_DONE			0x07
#define FRGMARK_STAGE_TIME_INIT_DONE			0x08
#define FRGMARK_STAGE_DRIVER_INIT_BEGIN			0x09
#define FRGMARK_STAGE_DRIVER_INIT_DONE			0x0a
#define FRGMARK_STAGE_KERNEL_INIT_BEGIN			0x0b
#define FRGMARK_STAGE_KERNEL_INIT_FREEABLE_DONE		0x0c
#define FRGMARK_STAGE_INITCALLS_BEGIN			0x0d
#define FRGMARK_STAGE_INITCALLS_DONE			0x0e
#define FRGMARK_STAGE_KERNEL_FREEABLE_DONE		0x0f
#define FRGMARK_STAGE_EXEC_RAMDISK_INIT			0x10
#define FRGMARK_STAGE_EXEC_RAMDISK_INIT_FAILED		0x11
#define FRGMARK_STAGE_EXEC_CMDLINE_INIT			0x12
#define FRGMARK_STAGE_EXEC_FALLBACK_INIT		0x13
#define FRGMARK_STAGE_CONSOLE_INIT_DONE			0x14

#define FRGMARK_STAGE_MSM_DRM_REGISTER_BEGIN		0x20
#define FRGMARK_STAGE_MSM_DRM_REGISTER_DONE		0x21
#define FRGMARK_STAGE_MSM_DRM_PROBE_BEGIN		0x22
#define FRGMARK_STAGE_MSM_DRM_COMPONENTS_DONE		0x23
#define FRGMARK_STAGE_MSM_DRM_BIND_BEGIN		0x24
#define FRGMARK_STAGE_MSM_DRM_DEV_REGISTER_DONE		0x25
#define FRGMARK_STAGE_MSM_DRM_SPLASH_DONE		0x26
#define FRGMARK_STAGE_MSM_DRM_FBDEV_DONE		0x27
#define FRGMARK_STAGE_MSM_DRM_REGISTER_FAILED		0x2f

#define FRGMARK_STAGE_DSI_REGISTER_BEGIN		0x30
#define FRGMARK_STAGE_DSI_REGISTER_DONE			0x31
#define FRGMARK_STAGE_DSI_DISPLAY_PROBE_BEGIN		0x32
#define FRGMARK_STAGE_DSI_DISPLAY_ACTIVE_INIT_BEGIN	0x33
#define FRGMARK_STAGE_DSI_DISPLAY_ACTIVE_INIT_DONE	0x34
#define FRGMARK_STAGE_DSI_DISPLAY_COMPONENT_DONE	0x35
#define FRGMARK_STAGE_DSI_REGISTER_FAILED		0x3f

#define FRGMARK_STAGE_HEARTBEAT_BASE			0x40
#define FRGMARK_STAGE_HEARTBEAT_LAST			0x4f

#ifdef CONFIG_ARM64
void __init frgmark_init_iomap(void);
void frgmark(u8 stage);
#else
static inline void frgmark_init_iomap(void) {}
static inline void frgmark(u8 stage) {}
#endif

#endif /* _LINUX_FRGMARK_H */
