#---------------------------PROX SENSOR---------------------------------#
obj-$(CONFIG_NUBIA_SENSORS_PROX_PA224)		+= txc_pa224.o
#---------------------------RGB SENSOR----------------------------------#
obj-$(CONFIG_NUBIA_SENSORS_RGB_BH1745)		+= rohm_bh1745.o
